# Generated by Django 3.2.8 on 2021-10-22 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20211022_0807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salaryhighest',
            name='highest',
        ),
        migrations.RemoveField(
            model_name='salarylowest',
            name='lowest',
        ),
        migrations.DeleteModel(
            name='ReportSalary',
        ),
        migrations.DeleteModel(
            name='SalaryHighest',
        ),
        migrations.DeleteModel(
            name='SalaryLowest',
        ),
    ]
