# Generated by Django 3.2.8 on 2021-10-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0005_auto_20211022_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportAge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('younger', models.TextField()),
                ('older', models.TextField()),
                ('average', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='ReportSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lowest', models.TextField()),
                ('highest', models.TextField()),
                ('average', models.CharField(max_length=6)),
            ],
        ),
    ]
