# Generated by Django 3.2.8 on 2021-10-22 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_department'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average', models.DecimalField(decimal_places=2, max_digits=6)),
                ('highest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highest', to='employees.employee')),
                ('lowest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lowest', to='employees.employee')),
            ],
        ),
        migrations.RemoveField(
            model_name='salarylowest',
            name='lowest',
        ),
        migrations.DeleteModel(
            name='SalaryHighest',
        ),
        migrations.DeleteModel(
            name='SalaryLowest',
        ),
    ]
