# Generated by Django 3.2.8 on 2021-10-22 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_department'),
        ('reports', '0002_auto_20211022_0753'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryLowest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lowest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryHighest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
        ),
        migrations.AlterField(
            model_name='reportsalary',
            name='highest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.salaryhighest'),
        ),
        migrations.AlterField(
            model_name='reportsalary',
            name='lowest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.salarylowest'),
        ),
    ]
