# Generated by Django 3.2.8 on 2021-10-22 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20211022_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsalary',
            name='highest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.salaryhighest'),
        ),
        migrations.AlterField(
            model_name='reportsalary',
            name='lowest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.salarylowest'),
        ),
    ]
